import gradio as gr
import plotly.graph_objects as go

import io
import datetime
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether,
)

# ============================================================================
# GMP Pilot-to-Production Readiness Simulator
# Unofficial portfolio prototype. Not affiliated with any specific vendor.
# Built on publicly available pharma industry references.
# ============================================================================

APP_TITLE = "GMP Pilot-to-Production Readiness Simulator"
APP_TAGLINE = (
    "An illustrative assessment tool for pharma manufacturing leaders "
    "evaluating whether their factories are ready to roll out AI-powered "
    "line clearance — before committing budget."
)
APP_DISCLAIMER = (
    "Illustrative sample report generated by an unofficial portfolio "
    "prototype. Not affiliated with or endorsed by any specific vendor. "
    "Built on publicly available pharma industry references and "
    "conservative modeling assumptions."
)

COLORS = {
    "primary":      "#1a2b4a",
    "accent":       "#2c8a8a",
    "secondary":    "#d68910",
    "risk_high":    "#a94442",
    "risk_medium":  "#d68910",
    "risk_low":     "#1e7e34",
    "panel_bg":     "#f8f9fb",
    "text_primary": "#1a2b4a",
    "text_muted":   "#5a6478",
    "border":       "#dde2ec",
}

CUSTOM_CSS = f"""
.gradio-container {{
    max-width: 1100px !important;
    margin: 0 auto !important;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}}
#header-banner {{
    background: linear-gradient(135deg, {COLORS['primary']} 0%, #2a4070 100%);
    color: white;
    padding: 32px 36px;
    border-radius: 8px;
    margin-bottom: 24px;
}}
#header-banner h1 {{
    color: white !important;
    font-size: 28px !important;
    font-weight: 600 !important;
    margin: 0 0 8px 0 !important;
}}
#header-banner p {{
    color: #c8d2e6 !important;
    font-size: 15px !important;
    margin: 0 !important;
    line-height: 1.5 !important;
}}
#disclaimer-strip {{
    background: #fffbeb;
    border-left: 3px solid {COLORS['secondary']};
    padding: 10px 16px;
    margin: 0 0 20px 0;
    font-size: 12px;
    color: {COLORS['text_muted']};
    border-radius: 0 4px 4px 0;
}}
#headline-card {{
    background: white;
    border: 1px solid {COLORS['border']};
    border-radius: 8px;
    padding: 28px 36px;
    margin: 16px 0 24px 0;
    box-shadow: 0 1px 3px rgba(26, 43, 74, 0.06);
}}
.results-section {{
    background: white;
    border: 1px solid {COLORS['border']};
    border-radius: 8px;
    padding: 24px 32px;
    margin-bottom: 16px;
}}
.results-section h2 {{
    color: {COLORS['primary']} !important;
    font-size: 20px !important;
    font-weight: 600 !important;
    margin-top: 0 !important;
    padding-bottom: 12px !important;
    border-bottom: 2px solid {COLORS['accent']} !important;
}}
.results-section h3 {{
    color: {COLORS['primary']} !important;
    font-size: 16px !important;
    font-weight: 600 !important;
    margin-top: 20px !important;
}}
table {{
    width: 100% !important;
    border-collapse: collapse !important;
    margin: 12px 0 !important;
}}
th {{
    background: {COLORS['panel_bg']} !important;
    color: {COLORS['primary']} !important;
    font-weight: 600 !important;
    text-align: left !important;
    padding: 10px 14px !important;
    border-bottom: 2px solid {COLORS['border']} !important;
    font-size: 13px !important;
}}
td {{
    padding: 10px 14px !important;
    border-bottom: 1px solid {COLORS['border']} !important;
    font-size: 14px !important;
    color: {COLORS['text_primary']} !important;
    vertical-align: top !important;
}}
button.primary {{
    background: {COLORS['primary']} !important;
    border-color: {COLORS['primary']} !important;
}}
button.primary:hover {{
    background: #2a4070 !important;
}}
"""


WEIGHTS = {"process": 0.30, "organizational": 0.30, "regulatory": 0.25, "technical": 0.15}

SCORE_CURRENT_METHOD = {
    "Fully paper-based": 10, "Hybrid (some digital, some paper)": 40,
    "Partially digitized": 70, "Mostly digital": 95,
}
SCORE_CLEARANCE_DURATION = {
    "Under 30 minutes": 90, "30–60 minutes": 70, "1–2 hours": 45, "Over 2 hours": 20,
}
SCORE_DEVIATION_FREQUENCY = {"None": 100, "1–2": 75, "3–5": 45, "6 or more": 15}
SCORE_OPERATOR_FAMILIARITY = {"High": 90, "Medium": 60, "Low": 25}
SCORE_PRIOR_ATTEMPT = {
    "Yes — successful": 95, "No — first attempt": 60, "Yes — stalled or failed": 25,
}
SCORE_INSPECTION_OUTCOME = {
    "Clean (no observations)": 95, "Minor observations": 70,
    "Major observations": 25, "Not applicable / never inspected": 55,
}
SCORE_VALIDATION_MATURITY = {
    "Mature (templates, dedicated team)": 95, "Functional but ad-hoc": 55, "Underdeveloped": 20,
}
SCORE_MES_SYSTEM = {
    "SAP": 80, "Werum PAS-X": 90, "Rockwell": 75, "Tulip": 70,
    "Other / Custom": 40, "None": 25,
}
SCORE_EBR_SYSTEM = {"Yes": 90, "Partial": 55, "No": 25}
SCORE_EQUIPMENT_AGE = {
    "Mostly under 5 years": 90, "Mixed (some new, some old)": 60, "Mostly over 10 years": 30,
}

VERDICT_BANDS = [
    (80, 100, "Ready to scale",
     "Proceed with full rollout planning. Risks are manageable; ROI is defensible."),
    (65, 79, "Ready with caveats",
     "Address the flagged risks before committing to a full rollout. "
     "Most readiness gaps are closeable in 1–3 months."),
    (45, 64, "Not yet ready",
     "Significant gaps to close first. A premature rollout is likely to stall. "
     "Focus on the lowest-scoring sub-category before reassessing."),
    (0, 44, "High risk",
     "Recommend additional limited pilot scope rather than a full rollout. "
     "Foundational gaps in process, organization, or regulation need attention first."),
]

DEFAULT_LABOR_RATE_USD_PER_HOUR = 65
DEFAULT_TIME_SAVINGS_PCT = 45
DEFAULT_FIRST_LINE_COST_USD = 90_000
DEFAULT_ADDITIONAL_LINE_COST_USD = 55_000
DEFAULT_DOWNTIME_COST_PER_HOUR_USD = 0   # NEW: user-adjustable, defaults to 0
NUM_OPERATORS_PER_CLEARANCE = 2
WEEKS_PER_YEAR = 48

DURATION_TO_HOURS = {
    "Under 30 minutes": 0.4, "30–60 minutes": 0.75, "1–2 hours": 1.5, "Over 2 hours": 2.5,
}


# ============================================================================
# SAMPLE SCENARIO — for the "Load sample scenario" button
# ============================================================================

SAMPLE_SCENARIO = {
    "num_lines": 18,
    "num_facilities": 2,
    "annual_volume": "10–100 million units",
    "product_type": "Oral solid dose",
    "current_method": "Hybrid (some digital, some paper)",
    "clearance_duration": "1–2 hours",
    "changeovers_per_week": 6,
    "deviation_frequency": "3–5",
    "mes_system": "SAP",
    "ebr_system": "Partial",
    "equipment_age": "Mixed (some new, some old)",
    "inspection_outcome": "Minor observations",
    "validation_maturity": "Functional but ad-hoc",
    "operator_familiarity": "Medium",
    "prior_attempt": "No — first attempt",
    "labor_rate": 65,
    "time_savings_pct": 45,
    "first_line_cost": 90_000,
    "additional_line_cost": 55_000,
    "downtime_cost_per_hour": 1000,
}


# ============================================================================
# RISK RULES
# ============================================================================

def risk_legacy_integration(mes_system, ebr_system, equipment_age, **_):
    if mes_system == "None" and ebr_system == "No":
        return "High", ("No MES and no eBR in place — integration with an AI-powered "
            "line clearance platform would require building both upstream systems "
            "first, adding 6–12 months before deployment.")
    if mes_system in ("None", "Other / Custom") or ebr_system == "No":
        return "Medium", (f"MES setup ({mes_system}) and eBR coverage ({ebr_system}) will "
            "require additional integration work — plan 2–4 months of IT effort.")
    if equipment_age == "Mostly over 10 years":
        return "Medium", ("Equipment is mostly over 10 years old; PLC and sensor "
            "compatibility checks will likely surface integration edge cases.")
    ebr_descriptor = "strong" if ebr_system == "Yes" else "in-place"
    return "Low", (f"Modern MES ({mes_system}) and {ebr_descriptor} eBR coverage "
        f"({ebr_system}) make integration straightforward.")


def risk_validation_backlog(validation_maturity, num_lines, num_facilities, **_):
    if validation_maturity == "Underdeveloped":
        return "High", ("CSV maturity is underdeveloped — IQ/OQ/PQ authoring for "
            f"{num_lines} lines will become the rollout bottleneck.")
    if validation_maturity == "Functional but ad-hoc" and num_lines > 15:
        return "High", (f"Validation is ad-hoc, and rollout scope is {num_lines} "
            "lines. Documentation will slip behind deployment.")
    if validation_maturity == "Functional but ad-hoc":
        return "Medium", ("Validation is functional but ad-hoc — manageable at "
            "this scale, but build templates before further expansion.")
    if num_facilities > 1:
        return "Medium", ("Strong validation, but multi-site rollout requires "
            "harmonizing templates across sites — coordinate early.")
    return "Low", ("Mature validation function can absorb the rollout workload "
        "without becoming a bottleneck.")


def risk_operator_adoption(operator_familiarity, current_method, **_):
    if operator_familiarity == "Low" and current_method == "Fully paper-based":
        return "High", ("Operators have low digital familiarity and work fully "
            "on paper. Budget 2–3 months of training before go-live.")
    if operator_familiarity == "Low":
        return "High", ("Operator digital familiarity is low — adoption needs "
            "deliberate training, change agents, and visible leadership support.")
    if operator_familiarity == "Medium":
        return "Medium", ("Mixed operator familiarity — identify and train "
            "change-champion operators first to lead by example.")
    return "Low", ("High operator digital familiarity — adoption is unlikely "
        "to be a blocker. Standard training program should suffice.")


def risk_multi_site_coordination(num_facilities, num_lines, **_):
    if num_facilities == 1:
        return "Low", "Single-site rollout — no inter-site coordination overhead."
    if num_facilities <= 3:
        return "Medium", (f"{int(num_facilities)} facilities involved — "
            "establish central program management before kickoff.")
    return "High", (f"{int(num_facilities)} facilities — multi-site rollouts "
        "at this scale need PMO, harmonized templates, and sequenced go-live.")


def risk_sponsorship(prior_attempt, operator_familiarity, **_):
    if prior_attempt == "Yes — stalled or failed":
        return "High", ("Prior attempt stalled or failed — sponsorship is likely "
            "thin or fades under pressure. Re-engage sponsors with clear remit.")
    if prior_attempt == "No — first attempt" and operator_familiarity == "Low":
        return "Medium", ("First attempt with low operator familiarity — "
            "sponsorship will be tested under friction. Document commitment.")
    if prior_attempt == "Yes — successful":
        return "Low", ("Previous success implies established sponsorship and "
            "an organization that knows how to deliver these projects.")
    return "Medium", ("First-time attempt — sponsorship strength unproven. "
        "Secure explicit, named, written commitment before kickoff.")


def risk_change_control(validation_maturity, deviation_frequency, **_):
    if validation_maturity == "Underdeveloped" and deviation_frequency in ("3–5", "6 or more"):
        return "High", (f"QA absorbing {deviation_frequency} deviations/year "
            "against underdeveloped validation. New submissions will queue.")
    if deviation_frequency == "6 or more":
        return "High", ("Six or more deviations per year — quality system "
            "overloaded. New change-control will compete for QA bandwidth.")
    if validation_maturity == "Functional but ad-hoc" and deviation_frequency in ("3–5", "6 or more"):
        return "Medium", ("Ad-hoc validation + elevated deviations — QA "
            "bandwidth tight. Schedule change-control during quieter windows.")
    return "Low", ("Quality system has bandwidth to handle the change-control "
        "submission alongside business as usual.")


def risk_pilot_fatigue(prior_attempt, **_):
    if prior_attempt == "Yes — stalled or failed":
        return "High", ("Prior digitization attempt stalled or failed. Without "
            "clear post-mortem, organizational skepticism will undermine restart.")
    if prior_attempt == "No — first attempt":
        return "Low", ("First attempt — no historical baggage. Use clean slate "
            "to establish a track record.")
    return "Low", ("Previous successful attempt creates positive momentum and "
        "internal advocates.")


def risk_equipment_compatibility(equipment_age, mes_system, **_):
    if equipment_age == "Mostly over 10 years":
        return "High", ("Equipment mostly over 10 years old — expect PLC "
            "firmware mismatches and sensor compatibility issues.")
    if equipment_age == "Mixed (some new, some old)" and mes_system in ("None", "Other / Custom"):
        return "Medium", ("Mixed-age equipment + no standard MES — line-level "
            "data extraction will vary. Catalog by line before committing.")
    if equipment_age == "Mixed (some new, some old)":
        return "Medium", ("Mixed-age equipment — newer lines will go live "
            "faster; older lines may need targeted upgrades.")
    return "Low", ("Modern equipment fleet — sensor and PLC integration "
        "should be straightforward.")


RISK_RULES = [
    ("Legacy MES/ERP integration", risk_legacy_integration),
    ("Validation documentation backlog", risk_validation_backlog),
    ("Operator adoption & training", risk_operator_adoption),
    ("Multi-site coordination", risk_multi_site_coordination),
    ("Executive sponsorship fragility", risk_sponsorship),
    ("Change-control / QA bottleneck", risk_change_control),
    ("Past-failure / pilot fatigue", risk_pilot_fatigue),
    ("Equipment age & PLC compatibility", risk_equipment_compatibility),
]


# ============================================================================
# RECOMMENDATIONS
# ============================================================================

def rec_regulatory_observations(inspection_outcome, **_):
    if inspection_outcome == "Major observations":
        return (1, "**Resolve outstanding regulatory observations first.** Adding "
            "new validation scope while major observations are open creates regulatory "
            "exposure. Close CAPA actions before initiating any deployment work.")
    return None


def rec_validation_capacity(validation_maturity, num_lines, **_):
    if validation_maturity == "Underdeveloped":
        return (1, f"**Build validation templates before scoping.** Validation maturity "
            f"is underdeveloped, targeting {num_lines} lines. Without reusable IQ/OQ/PQ "
            "templates, documentation will consume your QA team.")
    if validation_maturity == "Functional but ad-hoc" and num_lines > 15:
        return (2, f"**Strengthen validation templates before scaling to "
            f"{num_lines} lines.** Ad-hoc validation can keep up at small scale, but "
            f"at {num_lines} lines documentation will fall behind deployment. Invest "
            "in reusable IQ/OQ/PQ templates and a dedicated CSV lead before kickoff.")
    return None


def rec_prior_attempt_postmortem(prior_attempt, **_):
    if prior_attempt == "Yes — stalled or failed":
        return (2, "**Conduct a post-mortem on the previous attempt before restarting.** "
            "Identify what failed (sponsorship, tech, change management), document it, "
            "and explicitly state what's different this time.")
    return None


def rec_sponsorship(prior_attempt, operator_familiarity, **_):
    if prior_attempt == "Yes — stalled or failed":
        return (2, "**Re-engage executive sponsorship with a documented remit.** "
            "Sponsor commitment must be explicit, named, and documented — verbal "
            "endorsement won't survive the first friction.")
    if prior_attempt == "No — first attempt" and operator_familiarity == "Low":
        return (4, "**Confirm and document executive sponsorship before kickoff.** "
            "Get written commitment from a named executive with budget authority.")
    return None


def rec_ebr_first(ebr_system, mes_system, **_):
    if ebr_system == "No":
        return (3, "**Establish electronic batch record coverage first.** "
            "Without eBR, the AI line clearance integration must build the batch-record "
            "interface from scratch, adding months and creating a single point of failure.")
    return None


def rec_mes_strategy(mes_system, **_):
    if mes_system == "None":
        return (3, "**Define an MES strategy before scoping.** With no MES, an AI line "
            "clearance platform has nothing to receive batch context from. Choose whether "
            "to deploy a pharma-grade MES in parallel or scope as standalone.")
    return None


def rec_qa_capacity(validation_maturity, deviation_frequency, **_):
    if validation_maturity == "Underdeveloped" and deviation_frequency in ("3–5", "6 or more"):
        return (1, f"**Address QA capacity before adding new change-control "
            f"submissions.** You have {deviation_frequency} deviations/year against "
            "underdeveloped validation. New submissions will queue behind existing CAPAs.")
    if deviation_frequency == "6 or more":
        return (4, "**Run a deviation-reduction sprint before adding scope.** Six or "
            "more deviations per year suggests the underlying process is unstable.")
    return None


def rec_operator_training(operator_familiarity, current_method, **_):
    if operator_familiarity == "Low" and current_method == "Fully paper-based":
        return (4, "**Build operator readiness before go-live.** Operators moving from "
            "fully paper-based to AI-assisted need structured training, change champions, "
            "and shadow-operation periods. Budget 2–3 months.")
    if operator_familiarity == "Low":
        return (4, "**Identify and train change-champion operators on each shift.** "
            "Low overall familiarity is overcome by visible peer adoption.")
    return None


def rec_equipment_audit(equipment_age, **_):
    if equipment_age == "Mostly over 10 years":
        return (3, "**Conduct a line-by-line equipment audit before scoping.** With "
            "equipment mostly over 10 years old, expect PLC firmware mismatches. "
            "Some lines may need upgrades before AI line clearance can be deployed.")
    return None


def rec_multi_site_pmo(num_facilities, **_):
    if num_facilities >= 4:
        return (5, f"**Establish a dedicated PMO for the {int(num_facilities)}-site "
            "rollout.** Central program management, harmonized templates, and "
            "sequenced site-by-site go-live are non-negotiable at this scale.")
    if num_facilities in (2, 3):
        return (5, f"**Designate a central rollout lead across the "
            f"{int(num_facilities)} facilities.** Even at small multi-site scale, "
            "one accountable owner prevents divergence.")
    return None


def rec_pilot_scope(prior_attempt, num_lines, **_):
    if prior_attempt == "Yes — stalled or failed" and num_lines > 5:
        return (5, f"**Reduce initial scope from {num_lines} lines to 2–3 lines for "
            "the restart.** A focused restart with visible early wins rebuilds "
            "organizational confidence faster than a broad rollout.")
    return None


RECOMMENDATION_RULES = [
    rec_regulatory_observations, rec_validation_capacity, rec_prior_attempt_postmortem,
    rec_sponsorship, rec_ebr_first, rec_mes_strategy, rec_qa_capacity,
    rec_operator_training, rec_equipment_audit, rec_multi_site_pmo, rec_pilot_scope,
]


# ============================================================================
# ENGINES
# ============================================================================

def compute_readiness_score(
    current_method, clearance_duration, deviation_frequency,
    operator_familiarity, prior_attempt, inspection_outcome, validation_maturity,
    mes_system, ebr_system, equipment_age,
):
    process_score = (SCORE_CURRENT_METHOD[current_method]
        + SCORE_CLEARANCE_DURATION[clearance_duration]
        + SCORE_DEVIATION_FREQUENCY[deviation_frequency]) / 3
    org_score = (SCORE_OPERATOR_FAMILIARITY[operator_familiarity]
        + SCORE_PRIOR_ATTEMPT[prior_attempt]) / 2
    reg_score = (SCORE_INSPECTION_OUTCOME[inspection_outcome]
        + SCORE_VALIDATION_MATURITY[validation_maturity]) / 2
    tech_score = (SCORE_MES_SYSTEM[mes_system]
        + SCORE_EBR_SYSTEM[ebr_system]
        + SCORE_EQUIPMENT_AGE[equipment_age]) / 3
    total = (process_score * WEIGHTS["process"]
        + org_score * WEIGHTS["organizational"]
        + reg_score * WEIGHTS["regulatory"]
        + tech_score * WEIGHTS["technical"])

    verdict_label, verdict_message = "", ""
    for low, high, label, message in VERDICT_BANDS:
        if low <= total <= high:
            verdict_label, verdict_message = label, message
            break

    return {
        "total": round(total, 1),
        "process": round(process_score, 1),
        "organizational": round(org_score, 1),
        "regulatory": round(reg_score, 1),
        "technical": round(tech_score, 1),
        "verdict_label": verdict_label,
        "verdict_message": verdict_message,
    }


def compute_roi(
    num_lines, num_facilities, changeovers_per_week, clearance_duration,
    labor_rate, time_savings_pct, first_line_cost, additional_line_cost,
    downtime_cost_per_hour=0,
):
    hours_per_clearance = DURATION_TO_HOURS[clearance_duration]
    annual_clearance_events = num_lines * changeovers_per_week * WEEKS_PER_YEAR
    labor_hours_per_event = hours_per_clearance * NUM_OPERATORS_PER_CLEARANCE
    current_annual_cost = annual_clearance_events * labor_hours_per_event * labor_rate
    post_rollout_cost = current_annual_cost * (1 - time_savings_pct / 100)
    labor_savings = current_annual_cost - post_rollout_cost

    # Downtime savings: hours saved (not counting QA witness — downtime is line-stopped time)
    # = annual_events × clearance_hours × (time_savings_pct/100) × downtime_cost_per_hour
    downtime_hours_saved = (annual_clearance_events * hours_per_clearance
                             * (time_savings_pct / 100))
    downtime_savings = downtime_hours_saved * downtime_cost_per_hour

    annual_savings = labor_savings + downtime_savings

    # Protection: never have more facilities than lines (would imply <1 line/site)
    effective_facilities = min(num_facilities, num_lines)
    lines_per_facility = max(1, num_lines / effective_facilities)
    deployment_cost = (effective_facilities * first_line_cost
        + effective_facilities * (lines_per_facility - 1) * additional_line_cost)
    payback_months = (deployment_cost / annual_savings) * 12 if annual_savings > 0 else None

    # 3-year net benefit
    three_year_net_benefit = (annual_savings * 3) - deployment_cost

    return {
        "annual_events": int(annual_clearance_events),
        "current_annual_cost": current_annual_cost,
        "post_rollout_cost": post_rollout_cost,
        "labor_savings": labor_savings,
        "downtime_savings": downtime_savings,
        "annual_savings": annual_savings,
        "deployment_cost": deployment_cost,
        "payback_months": payback_months,
        "three_year_net_benefit": three_year_net_benefit,
        "downtime_cost_per_hour": downtime_cost_per_hour,
    }


def compute_risk_heatmap(**inputs):
    return [(name, *rule_fn(**inputs)) for name, rule_fn in RISK_RULES]


def compute_recommendations(**inputs):
    candidates = []
    for rule_fn in RECOMMENDATION_RULES:
        result = rule_fn(**inputs)
        if result is not None:
            candidates.append(result)
    candidates.sort(key=lambda x: x[0])
    return [text for _, text in candidates[:7]]


# ============================================================================
# CHART BUILDERS
# ============================================================================

def get_score_color(score):
    if score >= 80: return COLORS["risk_low"]
    if score >= 65: return COLORS["accent"]
    if score >= 45: return COLORS["secondary"]
    return COLORS["risk_high"]


def build_readiness_gauge(score):
    color = get_score_color(score)
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=score,
        number={
            "font": {"size": 56, "color": COLORS["primary"], "family": "system-ui"},
            "suffix": "<span style='font-size:18px;color:#5a6478'> / 100</span>",
        },
        gauge={
            "axis": {"range": [0, 100], "tickwidth": 1,
                "tickcolor": COLORS["text_muted"],
                "tickfont": {"size": 11, "color": COLORS["text_muted"]},
                "tickvals": [0, 25, 50, 75, 100]},
            "bar": {"color": color, "thickness": 0.6},
            "bgcolor": COLORS["panel_bg"], "borderwidth": 0,
            "steps": [
                {"range": [0, 44], "color": "#fbe9e9"},
                {"range": [44, 64], "color": "#fdf1de"},
                {"range": [64, 79], "color": "#dfeff0"},
                {"range": [79, 100], "color": "#e2f0e6"},
            ],
            "threshold": {"line": {"color": COLORS["primary"], "width": 3},
                "thickness": 0.85, "value": score},
        },
        domain={"x": [0, 1], "y": [0, 1]},
    ))
    fig.update_layout(height=260, margin=dict(l=20, r=20, t=20, b=20),
        paper_bgcolor="white",
        font={"family": "system-ui", "color": COLORS["text_primary"]})
    return fig


def build_subscore_ladder(process, organizational, regulatory, technical):
    categories = ["Process", "Organizational", "Regulatory", "Technical"]
    weights = ["30%", "30%", "25%", "15%"]
    scores = [process, organizational, regulatory, technical]
    labels = [f"{c}  ·  {w} weight" for c, w in zip(categories, weights)]
    colors = [get_score_color(s) for s in scores]

    fig = go.Figure()
    fig.add_trace(go.Bar(y=labels, x=[100]*4, orientation="h",
        marker={"color": COLORS["panel_bg"]},
        hoverinfo="skip", showlegend=False, width=0.5))
    fig.add_trace(go.Bar(y=labels, x=scores, orientation="h",
        marker={"color": colors},
        text=[f"<b>{s:.0f}</b>" for s in scores],
        textposition="outside",
        textfont={"size": 14, "color": COLORS["primary"]},
        hovertemplate="<b>%{y}</b><br>Score: %{x:.1f}/100<extra></extra>",
        showlegend=False, width=0.4))

    fig.update_layout(
        barmode="overlay", height=260,
        margin=dict(l=30, r=60, t=10, b=20),
        paper_bgcolor="white", plot_bgcolor="white",
        xaxis={"range": [0, 110], "showgrid": False, "zeroline": False,
            "tickvals": [0, 25, 50, 75, 100],
            "tickfont": {"size": 11, "color": COLORS["text_muted"]}},
        yaxis={"showgrid": False,
            "tickfont": {"size": 13, "color": COLORS["primary"]},
            "autorange": "reversed"},
        font={"family": "system-ui"})
    return fig


def build_roi_comparison(current_cost, post_cost, savings):
    categories = ["Current annual cost<br>(manual line clearance)",
                  "Projected annual cost<br>(after AI line clearance rollout)"]
    values = [current_cost, post_cost]
    colors = [COLORS["text_muted"], COLORS["accent"]]
    fig = go.Figure()
    fig.add_trace(go.Bar(x=categories, y=values, marker={"color": colors},
        text=[f"<b>${v/1000:,.0f}K</b>" for v in values],
        textposition="outside",
        textfont={"size": 15, "color": COLORS["primary"]},
        hovertemplate="%{x}<br>%{y:$,.0f}<extra></extra>",
        width=0.5, showlegend=False))
    fig.add_annotation(x=0.5, y=max(values) * 1.08, xref="paper",
        text=f"<b>${savings/1000:,.0f}K saved/year</b>",
        showarrow=False,
        font={"size": 14, "color": COLORS["accent"]},
        bgcolor="white", bordercolor=COLORS["accent"],
        borderwidth=1.5, borderpad=8)
    fig.add_annotation(x=1, y=post_cost, ax=0, ay=current_cost,
        xref="x", yref="y", axref="x", ayref="y",
        showarrow=True, arrowhead=2, arrowsize=1.2,
        arrowwidth=2, arrowcolor=COLORS["accent"])
    fig.update_layout(height=340, margin=dict(l=40, r=40, t=70, b=60),
        paper_bgcolor="white", plot_bgcolor="white",
        xaxis={"showgrid": False,
            "tickfont": {"size": 12, "color": COLORS["primary"]}},
        yaxis={"showgrid": True, "gridcolor": COLORS["border"],
            "zeroline": False, "tickformat": "$,.0s",
            "tickfont": {"size": 11, "color": COLORS["text_muted"]},
            "range": [0, max(values) * 1.25]},
        font={"family": "system-ui"})
    return fig


def build_payback_timeline(payback_months):
    display_value = min(payback_months, 60) if payback_months else 60
    capped = payback_months and payback_months > 60

    if payback_months is None:
        bar_color = COLORS["risk_high"]
        verdict = "No projected payback"
    elif payback_months <= 24:
        bar_color = COLORS["risk_low"]
        verdict = "Within illustrative 24-month capital approval threshold"
    elif payback_months <= 36:
        bar_color = COLORS["accent"]
        verdict = "Above illustrative 24-month threshold — defensible with strategic case"
    else:
        bar_color = COLORS["secondary"]
        verdict = "Long payback — strategic case required"

    fig = go.Figure()
    fig.add_trace(go.Bar(y=["Payback"], x=[60], orientation="h",
        marker={"color": COLORS["panel_bg"]},
        hoverinfo="skip", showlegend=False, width=0.5))
    fig.add_trace(go.Bar(y=["Payback"], x=[display_value], orientation="h",
        marker={"color": bar_color},
        hovertemplate=f"<b>{payback_months:.1f} months</b><extra></extra>"
            if payback_months else "<extra></extra>",
        showlegend=False, width=0.4))

    # 24-month threshold line
    fig.add_shape(type="line", x0=24, x1=24, y0=-0.5, y1=0.5,
        line=dict(color=COLORS["primary"], width=2, dash="dash"))
    fig.add_annotation(x=24, y=0.5,
        text="Illustrative 24-month capital approval threshold",
        showarrow=False, yshift=18,
        font={"size": 11, "color": COLORS["primary"]})

    # NEW: Break-even marker at the actual payback value
    if payback_months and payback_months <= 60:
        fig.add_shape(type="line",
            x0=payback_months, x1=payback_months, y0=-0.4, y1=0.4,
            line=dict(color=COLORS["primary"], width=2.5))
        fig.add_annotation(x=payback_months, y=-0.45,
            text=f"<b>Break-even: month {payback_months:.1f}</b>",
            showarrow=False, yshift=-12,
            font={"size": 11, "color": COLORS["primary"]})

    label_text = (f"<b>{payback_months:.1f} months{' (capped)' if capped else ''}</b>"
        if payback_months else "<b>N/A</b>")
    fig.add_annotation(x=min(display_value + 2, 58), y=0,
        text=label_text, showarrow=False, xanchor="left",
        font={"size": 14, "color": COLORS["primary"]})
    fig.add_annotation(x=30, y=-0.95, text=f"<i>{verdict}</i>",
        showarrow=False,
        font={"size": 11, "color": COLORS["text_muted"]})
    fig.update_layout(barmode="overlay", height=200,
        margin=dict(l=20, r=20, t=40, b=50),
        paper_bgcolor="white", plot_bgcolor="white",
        xaxis={"range": [0, 62], "showgrid": False, "zeroline": False,
            "tickvals": [0, 12, 24, 36, 48, 60],
            "ticktext": ["0", "12 mo", "24 mo", "36 mo", "48 mo", "60+ mo"],
            "tickfont": {"size": 11, "color": COLORS["text_muted"]}},
        yaxis={"showticklabels": False, "showgrid": False, "zeroline": False,
            "range": [-1.4, 1.0]},
        font={"family": "system-ui"})
    return fig


def build_risk_heatmap_grid(risks):
    rating_color = {"High": COLORS["risk_high"], "Medium": COLORS["risk_medium"], "Low": COLORS["risk_low"]}
    rating_bg = {"High": "#f5e0e0", "Medium": "#fbeed3", "Low": "#dfe9e0"}

    rows, cols = 2, 4
    fig = go.Figure()

    for idx, (name, rating, explanation) in enumerate(risks):
        row = idx // cols
        col = idx % cols
        x0, x1 = col, col + 1
        y0, y1 = rows - row - 1, rows - row
        cx = (x0 + x1) / 2

        tagline = _make_tagline(explanation)

        fig.add_shape(type="rect",
            x0=x0 + 0.05, x1=x1 - 0.05,
            y0=y0 + 0.05, y1=y1 - 0.05,
            fillcolor=rating_bg[rating],
            line=dict(color=rating_color[rating], width=2),
            layer="below")
        fig.add_shape(type="rect",
            x0=x0 + 0.05, x1=x1 - 0.05,
            y0=y1 - 0.18, y1=y1 - 0.05,
            fillcolor=rating_color[rating],
            line=dict(width=0), layer="below")
        fig.add_annotation(x=cx, y=y1 - 0.115,
            text=f"<b>{rating.upper()}</b>",
            showarrow=False,
            font=dict(size=12, color="white", family="system-ui"))
        wrapped_name = _wrap_text(name, max_chars=20, max_lines=2)
        fig.add_annotation(x=cx, y=y1 - 0.35,
            text=f"<b>{wrapped_name}</b>",
            showarrow=False,
            font=dict(size=12, color=COLORS["primary"], family="system-ui"),
            align="center")
        wrapped_tagline = _wrap_text(tagline, max_chars=24, max_lines=3)
        fig.add_annotation(x=cx, y=y0 + 0.32,
            text=wrapped_tagline,
            showarrow=False,
            font=dict(size=10, color=COLORS["text_muted"], family="system-ui"),
            align="center")

    fig.update_layout(height=520,
        margin=dict(l=10, r=10, t=10, b=10),
        paper_bgcolor="white", plot_bgcolor="white",
        xaxis=dict(visible=False, range=[0, cols],
            showgrid=False, zeroline=False),
        yaxis=dict(visible=False, range=[0, rows],
            showgrid=False, zeroline=False),
        showlegend=False)
    return fig


def _make_tagline(explanation):
    for sep in [". ", " — ", " - ", ": "]:
        if sep in explanation:
            first = explanation.split(sep, 1)[0]
            if 10 < len(first) < 90:
                return first
    if len(explanation) <= 75:
        return explanation
    truncated = explanation[:75]
    last_space = truncated.rfind(" ")
    if last_space > 30:
        truncated = truncated[:last_space]
    return truncated + "…"


def _wrap_text(text, max_chars=24, max_lines=3):
    words = text.split()
    lines = []
    current = ""
    for word in words:
        if len(word) > max_chars:
            if current:
                lines.append(current)
                current = ""
            while len(word) > max_chars:
                lines.append(word[:max_chars])
                word = word[max_chars:]
            current = word
            continue
        candidate = (current + " " + word).strip()
        if len(candidate) <= max_chars:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    if len(lines) > max_lines:
        lines = lines[:max_lines]
        last = lines[-1]
        if len(last) > max_chars - 1:
            last = last[:max_chars - 1].rstrip()
        lines[-1] = last + "…"
    return "<br>".join(lines)


# ============================================================================
# PDF BUILDER
# ============================================================================

PDF_PRIMARY    = HexColor(COLORS["primary"])
PDF_ACCENT     = HexColor(COLORS["accent"])
PDF_SECONDARY  = HexColor(COLORS["secondary"])
PDF_HIGH       = HexColor(COLORS["risk_high"])
PDF_LOW        = HexColor(COLORS["risk_low"])
PDF_TEXT_MUTED = HexColor(COLORS["text_muted"])
PDF_BORDER     = HexColor(COLORS["border"])
PDF_PANEL_BG   = HexColor(COLORS["panel_bg"])


def _pdf_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="CoverTitle", fontName="Helvetica-Bold",
        fontSize=24, leading=30, textColor=PDF_PRIMARY,
        alignment=TA_LEFT, spaceAfter=12))
    styles.add(ParagraphStyle(name="CoverSubtitle", fontName="Helvetica",
        fontSize=14, leading=20, textColor=PDF_TEXT_MUTED,
        alignment=TA_LEFT, spaceAfter=18))
    styles.add(ParagraphStyle(name="CoverMeta", fontName="Helvetica",
        fontSize=10, leading=14, textColor=PDF_TEXT_MUTED, alignment=TA_LEFT))
    styles.add(ParagraphStyle(name="DisclaimerStyle", fontName="Helvetica-Oblique",
        fontSize=9, leading=12, textColor=PDF_TEXT_MUTED, alignment=TA_LEFT,
        spaceAfter=8))
    styles.add(ParagraphStyle(name="SectionHeading", fontName="Helvetica-Bold",
        fontSize=16, leading=20, textColor=PDF_PRIMARY,
        spaceBefore=8, spaceAfter=12))
    styles.add(ParagraphStyle(name="EyebrowLabel", fontName="Helvetica-Bold",
        fontSize=8, leading=12, textColor=PDF_TEXT_MUTED, spaceAfter=4))
    styles.add(ParagraphStyle(name="HeroNumber", fontName="Helvetica-Bold",
        fontSize=27, leading=31, textColor=PDF_PRIMARY, spaceAfter=4))
    styles.add(ParagraphStyle(name="HeroVerdict", fontName="Helvetica-Bold",
        fontSize=18, leading=22, textColor=PDF_PRIMARY, spaceAfter=6))
    styles.add(ParagraphStyle(name="BodyText2", fontName="Helvetica",
        fontSize=10, leading=15, textColor=PDF_PRIMARY, spaceAfter=8))
    styles.add(ParagraphStyle(name="Caption", fontName="Helvetica-Oblique",
        fontSize=8.5, leading=12, textColor=PDF_TEXT_MUTED, spaceAfter=6))
    return styles


def _draw_cover_decorations(canvas, doc):
    if doc.page == 1:
        canvas.saveState()
        canvas.setFillColor(PDF_PRIMARY)
        canvas.rect(0, LETTER[1] - 0.5 * inch, LETTER[0], 0.5 * inch, stroke=0, fill=1)
        canvas.setFillColor(PDF_ACCENT)
        canvas.rect(0.5 * inch, 0.5 * inch, 1.5 * inch, 4, stroke=0, fill=1)
        canvas.restoreState()


def _draw_page_chrome(canvas, doc):
    if doc.page > 1:
        canvas.saveState()
        canvas.setStrokeColor(PDF_BORDER)
        canvas.setLineWidth(0.5)
        canvas.line(0.5 * inch, LETTER[1] - 0.4 * inch,
                    LETTER[0] - 0.5 * inch, LETTER[1] - 0.4 * inch)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(PDF_TEXT_MUTED)
        canvas.drawString(0.5 * inch, LETTER[1] - 0.3 * inch,
                          "GMP Pilot-to-Production Readiness Simulator  ·  Executive Summary")
        canvas.drawRightString(LETTER[0] - 0.5 * inch, LETTER[1] - 0.3 * inch,
                               f"Page {doc.page}")
        canvas.line(0.5 * inch, 0.5 * inch,
                    LETTER[0] - 0.5 * inch, 0.5 * inch)
        canvas.setFont("Helvetica-Oblique", 7.5)
        canvas.drawString(0.5 * inch, 0.35 * inch,
                          "Illustrative sample report — GMP Pilot-to-Production Readiness Simulator (unofficial portfolio prototype)")
        canvas.restoreState()
    _draw_cover_decorations(canvas, doc)


def _fmt_money(x):
    return f"${x:,.0f}"


def _fmt_money_compact(x):
    """
    Compact money format for tight spaces (e.g., dashboard tiles).
    Uses K for thousands, M for millions, B for billions.
    """
    if x is None:
        return "N/A"
    abs_x = abs(x)
    if abs_x >= 1_000_000_000:
        return f"${x/1_000_000_000:.1f}B"
    if abs_x >= 10_000_000:
        return f"${x/1_000_000:.1f}M"
    if abs_x >= 1_000_000:
        return f"${x/1_000_000:.2f}M"
    if abs_x >= 1_000:
        return f"${x/1_000:,.0f}K"
    return f"${x:,.0f}"


def _build_cover_page(styles, score, roi):
    elements = []
    elements.append(Spacer(1, 1.2 * inch))

    elements.append(Paragraph("GMP Pilot-to-Production<br/>Readiness Simulator", styles["CoverTitle"]))
    elements.append(Paragraph("Executive Summary &amp; Business Case", styles["CoverSubtitle"]))

    elements.append(Paragraph(APP_DISCLAIMER, styles["DisclaimerStyle"]))

    elements.append(Spacer(1, 0.3 * inch))

    payback_str = (f"{roi['payback_months']:.1f} months"
                   if roi["payback_months"] is not None else "N/A")

    hero_data = [
        [Paragraph("READINESS VERDICT", styles["EyebrowLabel"]),
         Paragraph("PROJECTED PAYBACK", styles["EyebrowLabel"])],
        [Paragraph(score["verdict_label"], styles["HeroVerdict"]),
         Paragraph(payback_str, ParagraphStyle(
             name="PaybackHero", parent=styles["HeroVerdict"], textColor=PDF_ACCENT))],
        [Paragraph(f"Score: <b>{score['total']} / 100</b>", styles["BodyText2"]),
         Paragraph(f"Annual savings: <b>${roi['annual_savings']:,.0f}</b>", styles["BodyText2"])],
    ]
    hero_table = Table(hero_data, colWidths=[3.5 * inch, 3.5 * inch])
    hero_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("BACKGROUND", (0, 0), (-1, -1), PDF_PANEL_BG),
        ("LINEABOVE", (0, 0), (-1, 0), 0.5, PDF_BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 0.5, PDF_BORDER),
        ("LINEBEFORE", (0, 0), (0, -1), 0.5, PDF_BORDER),
        ("LINEAFTER", (-1, 0), (-1, -1), 0.5, PDF_BORDER),
        ("LINEBEFORE", (1, 0), (1, -1), 0.5, PDF_BORDER),
    ]))
    elements.append(hero_table)

    # NEW: 3-year net benefit on the cover
    elements.append(Spacer(1, 0.25 * inch))
    net_color = COLORS["risk_low"] if roi["three_year_net_benefit"] >= 0 else COLORS["risk_high"]
    elements.append(Paragraph(
        f"<b>3-Year Net Benefit:</b> "
        f"<font color='{net_color}'><b>${roi['three_year_net_benefit']:,.0f}</b></font>  "
        f"<font color='{COLORS['text_muted']}'>"
        f"(3 × annual savings − one-time deployment cost)</font>",
        styles["BodyText2"]
    ))

    elements.append(Spacer(1, 0.5 * inch))

    today = datetime.date.today().strftime("%B %d, %Y")
    elements.append(Paragraph(
        f"<b>Generated:</b> {today}<br/>"
        f"<b>Nature:</b> Illustrative sample report — generated by an unofficial portfolio prototype<br/>"
        f"<b>Methodology:</b> See appendix for full assumptions and sourcing",
        styles["CoverMeta"]
    ))

    elements.append(PageBreak())
    return elements


def _build_executive_summary_page(styles, score, roi, risks, recommendations,
                                  num_lines, num_facilities):
    elements = []
    elements.append(Paragraph("Executive Summary", styles["SectionHeading"]))
    elements.append(Spacer(1, 0.02 * inch))

    payback_str = (f"{roi['payback_months']:.1f} mo"
                   if roi["payback_months"] is not None else "N/A")

    metric_data = [
        [Paragraph("READINESS SCORE", styles["EyebrowLabel"]),
         Paragraph("PAYBACK", styles["EyebrowLabel"]),
         Paragraph("ANNUAL SAVINGS", styles["EyebrowLabel"]),
         Paragraph("3-YEAR NET BENEFIT", styles["EyebrowLabel"])],
        [Paragraph(f"{score['total']}", styles["HeroNumber"]),
         Paragraph(payback_str, styles["HeroNumber"]),
         Paragraph(_fmt_money_compact(roi['annual_savings']), styles["HeroNumber"]),
         Paragraph(_fmt_money_compact(roi['three_year_net_benefit']), styles["HeroNumber"])],
        [Paragraph(score["verdict_label"], styles["BodyText2"]),
         Paragraph("vs. illustrative 24-mo threshold", styles["Caption"]),
         Paragraph(f"per year at {num_lines} lines", styles["Caption"]),
         Paragraph("3 yr savings − deploy cost", styles["Caption"])],
    ]
    metric_table = Table(metric_data, colWidths=[1.75 * inch] * 4)
    metric_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, -1), PDF_PANEL_BG),
        ("LINEABOVE", (0, 0), (-1, 0), 0.5, PDF_BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 0.5, PDF_BORDER),
        ("LINEBEFORE", (0, 0), (0, -1), 0.5, PDF_BORDER),
        ("LINEAFTER", (-1, 0), (-1, -1), 0.5, PDF_BORDER),
        ("LINEBEFORE", (1, 0), (1, -1), 0.5, PDF_BORDER),
        ("LINEBEFORE", (2, 0), (2, -1), 0.5, PDF_BORDER),
        ("LINEBEFORE", (3, 0), (3, -1), 0.5, PDF_BORDER),
    ]))
    elements.append(metric_table)

    elements.append(Spacer(1, 0.3 * inch))

    high_count = sum(1 for _, r, _ in risks if r == "High")
    med_count  = sum(1 for _, r, _ in risks if r == "Medium")
    low_count  = sum(1 for _, r, _ in risks if r == "Low")

    elements.append(Paragraph("<b>Assessment overview</b>", styles["BodyText2"]))
    elements.append(Paragraph(f"{score['verdict_message']}", styles["BodyText2"]))

    elements.append(Paragraph("<b>Risk profile</b>", styles["BodyText2"]))
    elements.append(Paragraph(
        f"Of the 8 evaluated risks: "
        f"<font color='{COLORS['risk_high']}'><b>{high_count} High</b></font>, "
        f"<font color='{COLORS['risk_medium']}'><b>{med_count} Medium</b></font>, "
        f"<font color='{COLORS['risk_low']}'><b>{low_count} Low</b></font>. "
        "Detailed rationale in the Risk Register section.",
        styles["BodyText2"]))

    # Contextual explainer: when readiness is shaky but ROI looks strong
    if score["total"] < 65 and roi["payback_months"] is not None and roi["payback_months"] < 12:
        elements.append(Paragraph("<b>Why this looks contradictory</b>", styles["BodyText2"]))
        elements.append(Paragraph(
            "The financial case looks strong, yet the readiness score is below "
            "the &quot;Ready with caveats&quot; threshold. This is the exact pattern "
            "the simulator is designed to surface: factories with the most operational "
            "waste often have the strongest ROI on paper, but also the lowest probability "
            "of successfully capturing it. A premature rollout would likely stall before "
            "the savings are realized. Address the risks flagged below first; the "
            "financial upside will still be there.",
            styles["BodyText2"]))
    elements.append(Paragraph(
        f"{num_lines} production lines across {num_facilities} "
        f"{'facility' if num_facilities == 1 else 'facilities'}. "
        f"Estimated total deployment cost of <b>${roi['deployment_cost']:,.0f}</b>, "
        f"against current annual line clearance cost of "
        f"<b>${roi['current_annual_cost']:,.0f}</b>.",
        styles["BodyText2"]))

    if recommendations:
        elements.append(Spacer(1, 0.15 * inch))
        elements.append(Paragraph("<b>Top recommendation</b>", styles["BodyText2"]))
        top_rec = recommendations[0].replace("**", "")
        elements.append(Paragraph(top_rec, styles["BodyText2"]))
        remaining = len(recommendations) - 1
        if remaining > 0:
            elements.append(Paragraph(
                f"<i>{remaining} additional recommendation{'s' if remaining > 1 else ''} follow in the Next Steps section.</i>",
                styles["Caption"]))

    elements.append(PageBreak())
    return elements


def _build_factory_profile_page(styles, inputs):
    elements = []
    elements.append(Paragraph("Factory Profile", styles["SectionHeading"]))
    elements.append(Paragraph(
        "The assessment that follows is based on the inputs below. "
        "All defaults are conservative industry midpoints; users may "
        "override any input in the Advanced section of the web tool.",
        styles["BodyText2"]))
    elements.append(Spacer(1, 0.15 * inch))

    sections = [
        ("1. Factory Profile", [
            ("Production lines in scope", f"{int(inputs['num_lines'])}"),
            ("Facilities involved", f"{int(inputs['num_facilities'])}"),
            ("Annual production volume", inputs["annual_volume"]),
            ("Primary product type", inputs["product_type"])]),
        ("2. Current Line Clearance Practice", [
            ("Current method", inputs["current_method"]),
            ("Avg clearance duration", inputs["clearance_duration"]),
            ("Changeovers per line per week", f"{int(inputs['changeovers_per_week'])}"),
            ("Deviations in past 12 months", inputs["deviation_frequency"])]),
        ("3. IT and Integration Landscape", [
            ("Existing MES", inputs["mes_system"]),
            ("eBR system coverage", inputs["ebr_system"]),
            ("Equipment and PLC age", inputs["equipment_age"])]),
        ("4. Regulatory and Quality Context", [
            ("Last inspection outcome", inputs["inspection_outcome"]),
            ("CSV maturity", inputs["validation_maturity"])]),
        ("5. Workforce and Change Management", [
            ("Operator digital familiarity", inputs["operator_familiarity"]),
            ("Prior digitization attempt", inputs["prior_attempt"])]),
    ]

    for section_title, rows in sections:
        elements.append(Spacer(1, 0.10 * inch))
        elements.append(Paragraph(f"<b>{section_title}</b>",
            ParagraphStyle(name="ProfileSubsection", parent=styles["BodyText2"],
                textColor=PDF_PRIMARY, fontName="Helvetica-Bold",
                fontSize=10, spaceAfter=4)))
        table_data = []
        for label, value in rows:
            table_data.append([Paragraph(label, styles["BodyText2"]),
                Paragraph(f"<b>{value}</b>", styles["BodyText2"])])
        t = Table(table_data, colWidths=[2.7 * inch, 4.6 * inch])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LINEBELOW", (0, 0), (-1, -2), 0.3, PDF_BORDER),
            ("BACKGROUND", (0, 0), (-1, -1), HexColor("#fcfdfe")),
        ]))
        elements.append(t)

    elements.append(PageBreak())
    return elements


def _build_scorecard_page(styles, score):
    elements = []
    elements.append(Paragraph("Readiness Scorecard", styles["SectionHeading"]))
    elements.append(Paragraph(
        f"Overall readiness score: <b>{score['total']} / 100</b>  ·  "
        f"Verdict: <b>{score['verdict_label']}</b>", styles["BodyText2"]))
    elements.append(Spacer(1, 0.05 * inch))
    elements.append(Paragraph(score["verdict_message"], styles["BodyText2"]))
    elements.append(Spacer(1, 0.2 * inch))

    subscore_rows = [
        ("Process readiness", 30, score["process"],
         "Maturity of existing line clearance process. Reflects how digitized "
         "the operation already is, typical clearance duration, and recent deviations."),
        ("Organizational readiness", 30, score["organizational"],
         "Workforce digital familiarity and history with digital transformation. "
         "Past-attempt history is the single most predictive input in the model."),
        ("Regulatory readiness", 25, score["regulatory"],
         "Inspection posture and computer-system validation maturity. "
         "Underdeveloped CSV creates a documentation bottleneck during rollout."),
        ("Technical readiness", 15, score["technical"],
         "MES, eBR, and equipment compatibility. Weighted lowest because "
         "pharma rollouts more commonly fail on people and process, not technology."),
    ]

    header = [
        Paragraph("<b>Category</b>", styles["BodyText2"]),
        Paragraph("<b>Weight</b>", styles["BodyText2"]),
        Paragraph("<b>Score</b>", styles["BodyText2"]),
        Paragraph("<b>What this measures</b>", styles["BodyText2"]),
    ]
    rows = [header]
    for category, weight, sc, meaning in subscore_rows:
        if sc >= 80: color = COLORS["risk_low"]
        elif sc >= 65: color = COLORS["accent"]
        elif sc >= 45: color = COLORS["secondary"]
        else: color = COLORS["risk_high"]
        rows.append([
            Paragraph(f"<b>{category}</b>", styles["BodyText2"]),
            Paragraph(f"{weight}%", styles["BodyText2"]),
            Paragraph(f"<font color='{color}'><b>{sc:.0f} / 100</b></font>", styles["BodyText2"]),
            Paragraph(meaning, styles["BodyText2"])])
    score_table = Table(rows, colWidths=[1.5 * inch, 0.6 * inch, 0.9 * inch, 4.3 * inch])
    score_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), PDF_PANEL_BG),
        ("LINEBELOW", (0, 0), (-1, 0), 1, PDF_ACCENT),
        ("LINEBELOW", (0, 1), (-1, -2), 0.3, PDF_BORDER),
        ("LINEABOVE", (0, 0), (-1, 0), 0.3, PDF_BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 0.3, PDF_BORDER),
        ("LINEBEFORE", (0, 0), (0, -1), 0.3, PDF_BORDER),
        ("LINEAFTER", (-1, 0), (-1, -1), 0.3, PDF_BORDER),
    ]))
    elements.append(score_table)
    elements.append(PageBreak())
    return elements


def _build_financial_page(styles, roi, inputs):
    elements = []
    elements.append(Paragraph("Financial Projection", styles["SectionHeading"]))
    elements.append(Paragraph(
        "Projected economics if the deployment proceeds at the scope described. "
        "All figures use conservative midpoints of publicly available industry ranges; "
        "see the methodology appendix for sourcing.",
        styles["BodyText2"]))
    elements.append(Spacer(1, 0.15 * inch))

    payback_str = (f"{roi['payback_months']:.1f} months"
                   if roi["payback_months"] is not None else "Not applicable")
    downtime_line = (f"${roi['downtime_savings']:,.0f}"
        if roi["downtime_savings"] > 0 else "—  (downtime cost set to $0)")

    metric_rows = [
        ["Metric", "Value"],
        ["Annual line clearance events", f"{roi['annual_events']:,}"],
        ["Current annual line clearance cost", f"${roi['current_annual_cost']:,.0f}"],
        ["Projected post-rollout annual cost", f"${roi['post_rollout_cost']:,.0f}"],
        ["Annual labor savings", f"${roi['labor_savings']:,.0f}"],
        ["Annual downtime savings (optional)", downtime_line],
        ["Total annual savings", f"${roi['annual_savings']:,.0f}"],
        ["Estimated deployment cost (one-time)", f"${roi['deployment_cost']:,.0f}"],
        ["Payback period", payback_str],
        ["3-year net benefit", f"${roi['three_year_net_benefit']:,.0f}"],
    ]

    table_data = []
    for i, (label, value) in enumerate(metric_rows):
        is_header = i == 0
        if is_header:
            label_p = Paragraph(f"<b>{label}</b>", styles["BodyText2"])
            value_p = Paragraph(f"<b>{value}</b>", styles["BodyText2"])
        elif label in ("Total annual savings", "Payback period", "3-year net benefit"):
            color = COLORS["accent"] if label != "3-year net benefit" else (
                COLORS["risk_low"] if roi["three_year_net_benefit"] >= 0 else COLORS["risk_high"])
            label_p = Paragraph(f"<b>{label}</b>", styles["BodyText2"])
            value_p = Paragraph(f"<font color='{color}'><b>{value}</b></font>", styles["BodyText2"])
        else:
            label_p = Paragraph(label, styles["BodyText2"])
            value_p = Paragraph(value, styles["BodyText2"])
        table_data.append([label_p, value_p])

    fin_table = Table(table_data, colWidths=[4.4 * inch, 2.9 * inch])
    fin_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("BACKGROUND", (0, 0), (-1, 0), PDF_PANEL_BG),
        ("LINEBELOW", (0, 0), (-1, 0), 1, PDF_ACCENT),
        ("LINEBELOW", (0, 1), (-1, -2), 0.3, PDF_BORDER),
        ("BACKGROUND", (0, 6), (-1, 6), HexColor("#eaf3f3")),  # total annual savings row
        ("BACKGROUND", (0, 8), (-1, 8), HexColor("#eaf3f3")),  # payback row
        ("BACKGROUND", (0, 9), (-1, 9), HexColor("#eaf3f3")),  # 3-yr net benefit row
        ("LINEABOVE", (0, 0), (-1, 0), 0.3, PDF_BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 0.3, PDF_BORDER),
        ("LINEBEFORE", (0, 0), (0, -1), 0.3, PDF_BORDER),
        ("LINEAFTER", (-1, 0), (-1, -1), 0.3, PDF_BORDER),
    ]))
    elements.append(fin_table)

    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("<b>How this was calculated</b>", styles["BodyText2"]))
    elements.append(Paragraph(
        f"Annual events: {int(inputs['num_lines'])} lines × "
        f"{int(inputs['changeovers_per_week'])} changeovers/week × 48 production weeks.<br/>"
        f"Labor hours per event: midpoint of the duration band × 2 operators "
        f"(operator + QA witness, per GMP).<br/>"
        f"Labor rate: ${inputs['labor_rate']:.0f}/hour fully-loaded.<br/>"
        f"Time savings applied: {inputs['time_savings_pct']:.0f}% reduction in clearance time "
        "(vendor claim of 85% conservatively halved).<br/>"
        f"Downtime cost: ${inputs['downtime_cost_per_hour']:.0f}/hour "
        "(user-supplied — defaults to $0 to keep the base case conservative).<br/>"
        f"Deployment cost: ${inputs['first_line_cost']:,.0f} per first line across "
        f"{int(inputs['num_facilities'])} facilities, plus "
        f"${inputs['additional_line_cost']:,.0f} per additional line.",
        styles["BodyText2"]))
    elements.append(PageBreak())
    return elements


def _build_risk_register_page(styles, risks):
    elements = []
    elements.append(Paragraph("Risk Register", styles["SectionHeading"]))
    high_count = sum(1 for _, r, _ in risks if r == "High")
    med_count  = sum(1 for _, r, _ in risks if r == "Medium")
    low_count  = sum(1 for _, r, _ in risks if r == "Low")
    elements.append(Paragraph(
        f"Eight risks evaluated by rule-based logic against the inputs. "
        f"<font color='{COLORS['risk_high']}'><b>{high_count} High</b></font> · "
        f"<font color='{COLORS['risk_medium']}'><b>{med_count} Medium</b></font> · "
        f"<font color='{COLORS['risk_low']}'><b>{low_count} Low</b></font>.",
        styles["BodyText2"]))
    elements.append(Paragraph(
        "Each rationale references the specific inputs that drove its rating. "
        "Risks rated High should be addressed before committing to a full rollout; "
        "risks rated Medium typically resolve during rollout if proactively managed.",
        styles["Caption"]))
    elements.append(Spacer(1, 0.15 * inch))

    rating_color = {"High": COLORS["risk_high"], "Medium": COLORS["risk_medium"], "Low": COLORS["risk_low"]}
    rating_bg = {"High": HexColor("#f5e0e0"), "Medium": HexColor("#fbeed3"), "Low": HexColor("#dfe9e0")}

    header = [Paragraph("<b>Rating</b>", styles["BodyText2"]),
              Paragraph("<b>Risk</b>", styles["BodyText2"]),
              Paragraph("<b>Why this rating</b>", styles["BodyText2"])]
    rows = [header]
    style_commands = [
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("BACKGROUND", (0, 0), (-1, 0), PDF_PANEL_BG),
        ("LINEBELOW", (0, 0), (-1, 0), 1, PDF_ACCENT),
        ("LINEBELOW", (0, 1), (-1, -2), 0.3, PDF_BORDER),
        ("LINEABOVE", (0, 0), (-1, 0), 0.3, PDF_BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 0.3, PDF_BORDER),
        ("LINEBEFORE", (0, 0), (0, -1), 0.3, PDF_BORDER),
        ("LINEAFTER", (-1, 0), (-1, -1), 0.3, PDF_BORDER),
    ]
    for idx, (name, rating, explanation) in enumerate(risks):
        row_idx = idx + 1
        style_commands.append(("BACKGROUND", (0, row_idx), (0, row_idx), rating_bg[rating]))
        rating_cell = Paragraph(
            f"<font color='{rating_color[rating]}'><b>{rating.upper()}</b></font>", styles["BodyText2"])
        name_cell = Paragraph(f"<b>{name}</b>", styles["BodyText2"])
        expl_cell = Paragraph(explanation, styles["BodyText2"])
        rows.append([rating_cell, name_cell, expl_cell])

    risk_table = Table(rows, colWidths=[0.85 * inch, 2.0 * inch, 4.45 * inch])
    risk_table.setStyle(TableStyle(style_commands))
    elements.append(risk_table)
    elements.append(PageBreak())
    return elements


def _build_recommendations_page(styles, recommendations):
    elements = []
    elements.append(Paragraph("Next-Steps Recommendations", styles["SectionHeading"]))
    elements.append(Paragraph(
        "Prioritized actions to take <i>before</i> committing to a full rollout. "
        "Order reflects how pharma operations leaders typically sequence remediation: "
        "regulatory blockers first, then organizational scar tissue, then foundational "
        "technical gaps, then process improvements, then tactical optimizations.",
        styles["BodyText2"]))
    elements.append(Spacer(1, 0.15 * inch))

    if not recommendations:
        elements.append(Paragraph(
            "<b>No critical remediation required.</b> Your readiness score and "
            "risk profile suggest you can proceed directly to rollout planning. "
            "Standard project hygiene applies: secure budget, set milestones, "
            "and define success metrics before kickoff.", styles["BodyText2"]))
    else:
        for idx, text in enumerate(recommendations):
            clean = text.replace("**", "")
            if ". " in clean:
                head, _, tail = clean.partition(". ")
                head = head.strip() + "."
                tail = tail.strip()
                rec_text = f"<b>{head}</b> {tail}"
            else:
                rec_text = clean
            number_cell = Paragraph(
                f"<font color='{COLORS['accent']}'><b>{idx + 1}</b></font>",
                ParagraphStyle(name="RecNumber", parent=styles["BodyText2"],
                    fontSize=18, leading=22, alignment=TA_CENTER, textColor=PDF_ACCENT))
            body_cell = Paragraph(rec_text, styles["BodyText2"])
            rec_table = Table([[number_cell, body_cell]], colWidths=[0.55 * inch, 6.75 * inch])
            rec_table.setStyle(TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("BACKGROUND", (0, 0), (-1, -1), HexColor("#fcfdfe")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.3, PDF_BORDER),
                ("LINEABOVE", (0, 0), (-1, 0), 0.3, PDF_BORDER),
                ("LINEBEFORE", (0, 0), (0, -1), 3, PDF_ACCENT),
                ("LINEAFTER", (-1, 0), (-1, -1), 0.3, PDF_BORDER),
            ]))
            elements.append(rec_table)
            elements.append(Spacer(1, 0.08 * inch))
    elements.append(PageBreak())
    return elements


def _build_methodology_page(styles):
    elements = []
    elements.append(Paragraph("Appendix: Methodology &amp; Assumptions", styles["SectionHeading"]))
    elements.append(Paragraph(
        "This simulator is built on conservative midpoints of publicly available "
        "pharma industry data. Every numeric assumption is visible in the "
        "underlying code and can be audited or overridden. This appendix "
        "documents the assumptions and their sources so the analysis is "
        "defensible to a regulated-industry audience. " + APP_DISCLAIMER,
        styles["BodyText2"]))
    elements.append(Spacer(1, 0.15 * inch))

    def section(heading, body):
        elements.append(Paragraph(f"<b>{heading}</b>",
            ParagraphStyle(name="MethodSubsection", parent=styles["BodyText2"],
                fontName="Helvetica-Bold", textColor=PDF_PRIMARY,
                fontSize=11, spaceAfter=4, spaceBefore=8)))
        elements.append(Paragraph(body, styles["BodyText2"]))

    section("Readiness sub-score weightings",
        "Process 30% · Organizational 30% · Regulatory 25% · Technical 15%. "
        "These weightings reflect themes consistently discussed in publicly "
        "available pharma operations literature, where organizational and "
        "process risks are commonly identified as dominant causes of digital "
        "transformation failure — ranking ahead of technical risks. Public "
        "industry benchmark data shows that pilot-to-production scaling "
        "remains a persistent challenge across the sector.")

    section("Verdict bands",
        "80–100 Ready to scale · 65–79 Ready with caveats · 45–64 Not yet ready · "
        "0–44 High risk. Tightened upper-band cutoffs prevent false &quot;green "
        "light&quot; verdicts for middling factories.")

    section("Labor cost (fully-loaded operator)",
        "Default: $65/hour. Assumption basis: public industry references for "
        "pharma manufacturing operator base wages of approximately $25–30/hour, "
        "with fully-loaded cost typically running 2.0–2.5x base (benefits, "
        "overhead, supervision, indirect support). This puts a defensible "
        "fully-loaded rate in the ~$50–75/hour range. EU plants run higher; "
        "emerging markets lower. The user may override this in the Advanced "
        "section.")

    section("Time savings from AI line clearance",
        "Default: 45% reduction in clearance duration. Industry-leading AI line "
        "clearance vendors publicly market faster clearance gains in the 80%+ "
        "range. We deliberately use roughly half of typical vendor headlines "
        "because (a) vendor performance claims are typically aspirational, "
        "(b) real-world deployments capture only a fraction of demo-condition "
        "gains, and (c) a defensible business case is built on conservative "
        "assumptions, not best-case.")

    section("Downtime cost (optional, user-supplied)",
        "Default: $0/hour. Pharma production line downtime is genuinely costly "
        "($2,000–$20,000+/hour depending on product line) but estimates vary "
        "widely by product type and contract structure. Rather than embed an "
        "inflated default, the simulator leaves this at $0 and allows the user "
        "to add their own figure. The labor savings shown are therefore the "
        "conservative floor; downtime recovery is acknowledged upside.")

    section("Per-line deployment cost",
        "Defaults: $90,000 first line per facility · $55,000 each additional "
        "line in the same facility. Source basis: industry rule-of-thumb for "
        "enterprise machine vision deployments in pharma is $50K–$150K per "
        "line depending on complexity. We sit in the middle of the public range "
        "and assume the typical bulk-discount pattern of enterprise software.")

    section("Operational defaults",
        "Operators per clearance: 2 (operator + QA witness, per GMP). "
        "Production weeks per year: 48 (accounting for shutdowns, maintenance, "
        "holidays). Duration-band midpoints: Under 30 min → 0.4h · 30–60 min → "
        "0.75h · 1–2 hours → 1.5h · Over 2 hours → 2.5h.")

    section("What this simulator deliberately does not do",
        "It does not integrate with any real vendor system or API. It does not "
        "simulate the AI vision detection itself — it is a business and operational "
        "simulator. It does not generate IQ/OQ/PQ validation documents. It does "
        "not require login or save data. It does not claim ROI precision — it "
        "produces a defensible range with stated assumptions. It is not a sales "
        "tool — it is a neutral readiness assessment.")

    section("About the underlying research",
        "Publicly available 2025 pharma line clearance benchmark research "
        "(industry survey of 20,000+ pharma professionals) is referenced for "
        "the simulator's problem framing. Representative public findings: a "
        "majority of life sciences manufacturers still rely on paper-based "
        "line clearance; the majority reported at least one line clearance "
        "deviation in the past year; rogue components are widely cited as "
        "the leading cause of failures; and only a small minority have "
        "successfully digitized key components by 2025 despite many having "
        "piloted in earlier years.")

    return elements


def build_pdf(score, roi, risks, recommendations, inputs):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.65 * inch, bottomMargin=0.65 * inch,
        title="GMP Pilot-to-Production Readiness Simulator – Executive Summary",
        author="GMP Pilot-to-Production Readiness Simulator",
    )
    styles = _pdf_styles()
    elements = []
    elements.extend(_build_cover_page(styles, score, roi))
    elements.extend(_build_executive_summary_page(
        styles, score, roi, risks, recommendations,
        int(inputs["num_lines"]), int(inputs["num_facilities"])))
    elements.extend(_build_factory_profile_page(styles, inputs))
    elements.extend(_build_scorecard_page(styles, score))
    elements.extend(_build_financial_page(styles, roi, inputs))
    elements.extend(_build_risk_register_page(styles, risks))
    elements.extend(_build_recommendations_page(styles, recommendations))
    elements.extend(_build_methodology_page(styles))
    doc.build(elements, onFirstPage=_draw_page_chrome, onLaterPages=_draw_page_chrome)
    buffer.seek(0)
    return buffer


# ============================================================================
# UI HANDLERS
# ============================================================================

RATING_ICON = {"Low": "🟢 Low", "Medium": "🟡 Medium", "High": "🔴 High"}


def process_form(
    num_lines, num_facilities, annual_volume, product_type,
    current_method, clearance_duration, changeovers_per_week, deviation_frequency,
    mes_system, ebr_system, equipment_age,
    inspection_outcome, validation_maturity,
    operator_familiarity, prior_attempt,
    labor_rate, time_savings_pct, first_line_cost, additional_line_cost,
    downtime_cost_per_hour,
):
    score = compute_readiness_score(
        current_method, clearance_duration, deviation_frequency,
        operator_familiarity, prior_attempt,
        inspection_outcome, validation_maturity,
        mes_system, ebr_system, equipment_age)
    roi = compute_roi(
        num_lines, num_facilities, changeovers_per_week, clearance_duration,
        labor_rate, time_savings_pct, first_line_cost, additional_line_cost,
        downtime_cost_per_hour)
    common_inputs = dict(
        num_lines=num_lines, num_facilities=num_facilities,
        current_method=current_method, clearance_duration=clearance_duration,
        deviation_frequency=deviation_frequency,
        mes_system=mes_system, ebr_system=ebr_system, equipment_age=equipment_age,
        inspection_outcome=inspection_outcome, validation_maturity=validation_maturity,
        operator_familiarity=operator_familiarity, prior_attempt=prior_attempt)
    risks = compute_risk_heatmap(**common_inputs)
    recommendations = compute_recommendations(**common_inputs)

    payback_text = (f"{roi['payback_months']:.1f} months"
        if roi["payback_months"] is not None else "N/A")

    gauge_fig = build_readiness_gauge(score["total"])
    ladder_fig = build_subscore_ladder(
        score["process"], score["organizational"],
        score["regulatory"], score["technical"])
    roi_compare_fig = build_roi_comparison(
        roi["current_annual_cost"], roi["post_rollout_cost"], roi["annual_savings"])
    payback_fig = build_payback_timeline(roi["payback_months"])
    risk_grid_fig = build_risk_heatmap_grid(risks)

    # Headline card — now with 3-year net benefit
    net_color = COLORS["risk_low"] if roi["three_year_net_benefit"] >= 0 else COLORS["risk_high"]
    headline_html = f"""
<div id="headline-card">
  <div style="display:flex;align-items:center;justify-content:space-between;gap:32px;flex-wrap:wrap;">
    <div style="flex:1;min-width:280px;">
      <div style="font-size:13px;color:{COLORS['text_muted']};text-transform:uppercase;letter-spacing:1.5px;font-weight:600;margin-bottom:6px;">
        Readiness Verdict
      </div>
      <div style="font-size:28px;font-weight:700;color:{COLORS['primary']};line-height:1.2;margin-bottom:4px;">
        {score['verdict_label']}
      </div>
      <div style="font-size:14px;color:{COLORS['text_muted']};max-width:560px;line-height:1.5;">
        {score['verdict_message']}
      </div>
    </div>
    <div style="display:flex;gap:24px;">
      <div style="text-align:right;border-left:1px solid {COLORS['border']};padding-left:24px;">
        <div style="font-size:12px;color:{COLORS['text_muted']};text-transform:uppercase;letter-spacing:1.5px;font-weight:600;margin-bottom:4px;">
          Payback
        </div>
        <div style="font-size:24px;font-weight:700;color:{COLORS['accent']};line-height:1.1;">
          {payback_text}
        </div>
        <div style="font-size:12px;color:{COLORS['text_muted']};margin-top:6px;">
          Savings: <b>{_fmt_money_compact(roi['annual_savings'])}/yr</b>
        </div>
      </div>
      <div style="text-align:right;border-left:1px solid {COLORS['border']};padding-left:24px;">
        <div style="font-size:12px;color:{COLORS['text_muted']};text-transform:uppercase;letter-spacing:1.5px;font-weight:600;margin-bottom:4px;">
          3-Yr Net Benefit
        </div>
        <div style="font-size:24px;font-weight:700;color:{net_color};line-height:1.1;">
          {_fmt_money_compact(roi['three_year_net_benefit'])}
        </div>
        <div style="font-size:12px;color:{COLORS['text_muted']};margin-top:6px;">
          3 × savings − deploy cost
        </div>
      </div>
    </div>
  </div>
</div>
"""

    high_count = sum(1 for _, r, _ in risks if r == "High")
    med_count = sum(1 for _, r, _ in risks if r == "Medium")
    low_count = sum(1 for _, r, _ in risks if r == "Low")
    if recommendations:
        rec_block = "\n\n".join(f"{i+1}. {text}" for i, text in enumerate(recommendations))
    else:
        rec_block = ("**No critical remediation needed.** Your readiness score and "
            "risk profile suggest you can proceed directly to rollout planning.")

    downtime_note = ""
    if downtime_cost_per_hour > 0:
        downtime_note = (
            f"\n\n*Includes downtime cost of ${downtime_cost_per_hour:.0f}/hour, "
            f"adding ${roi['downtime_savings']:,.0f}/year in downtime savings.*")

    roi_notes_md = f"""
<div class="results-section">

### How the financial projection was calculated

- **Annual clearance events:** {num_lines} lines × {changeovers_per_week} changeovers/week × 48 production weeks/year = **{roi['annual_events']:,} events**
- **Labor hours per event:** {DURATION_TO_HOURS[clearance_duration]} hours × 2 operators (operator + QA witness, per GMP)
- **Labor rate used:** {_fmt_money(labor_rate)}/hour fully-loaded
- **Time savings applied:** {time_savings_pct}% (industry leaders publish ~85%; default conservatively halved)
- **Deployment cost:** {_fmt_money(first_line_cost)} per first line across {num_facilities} facilities, plus {_fmt_money(additional_line_cost)} per additional line
- **Total deployment cost:** **{_fmt_money(roi['deployment_cost'])}**
{downtime_note}

</div>
"""

    risk_summary_md = f"""
<div class="results-section">

### Risk Summary

🔴 **{high_count} High** · 🟡 **{med_count} Medium** · 🟢 **{low_count} Low**

*Each tile is determined by specific rules based on your inputs.
High-rated risks should be addressed before committing to a full rollout.*

</div>
"""

    risk_detail_rows = "\n".join(
        f"| {RATING_ICON[rating]} | **{name}** | {explanation} |"
        for name, rating, explanation in risks)
    risk_detail_md = f"""
<div class="results-section">

### Full risk rationale

| Rating | Risk | Why this rating |
|---|---|---|
{risk_detail_rows}

</div>
"""

    recommendations_md = f"""
<div class="results-section">

## Next-Steps Recommendation

Actions to take *before* committing to a full rollout, ordered by priority:

{rec_block}

</div>
"""

    return (
        headline_html, gauge_fig, ladder_fig,
        roi_compare_fig, payback_fig, roi_notes_md,
        risk_summary_md, risk_grid_fig, risk_detail_md, recommendations_md,
    )


def generate_pdf_for_download(
    num_lines, num_facilities, annual_volume, product_type,
    current_method, clearance_duration, changeovers_per_week, deviation_frequency,
    mes_system, ebr_system, equipment_age,
    inspection_outcome, validation_maturity,
    operator_familiarity, prior_attempt,
    labor_rate, time_savings_pct, first_line_cost, additional_line_cost,
    downtime_cost_per_hour,
):
    score = compute_readiness_score(
        current_method, clearance_duration, deviation_frequency,
        operator_familiarity, prior_attempt,
        inspection_outcome, validation_maturity,
        mes_system, ebr_system, equipment_age)
    roi = compute_roi(
        num_lines, num_facilities, changeovers_per_week, clearance_duration,
        labor_rate, time_savings_pct, first_line_cost, additional_line_cost,
        downtime_cost_per_hour)
    common_inputs = dict(
        num_lines=num_lines, num_facilities=num_facilities,
        current_method=current_method, clearance_duration=clearance_duration,
        deviation_frequency=deviation_frequency,
        mes_system=mes_system, ebr_system=ebr_system, equipment_age=equipment_age,
        inspection_outcome=inspection_outcome, validation_maturity=validation_maturity,
        operator_familiarity=operator_familiarity, prior_attempt=prior_attempt)
    risks = compute_risk_heatmap(**common_inputs)
    recommendations = compute_recommendations(**common_inputs)

    inputs = {
        **common_inputs,
        "annual_volume": annual_volume,
        "product_type": product_type,
        "changeovers_per_week": changeovers_per_week,
        "labor_rate": labor_rate,
        "time_savings_pct": time_savings_pct,
        "first_line_cost": first_line_cost,
        "additional_line_cost": additional_line_cost,
        "downtime_cost_per_hour": downtime_cost_per_hour,
    }

    buf = build_pdf(score, roi, risks, recommendations, inputs)
    import tempfile
    tmp = tempfile.NamedTemporaryFile(
        delete=False, suffix=".pdf",
        prefix=f"GMP_Readiness_{datetime.date.today().isoformat()}_")
    tmp.write(buf.read())
    tmp.close()
    return tmp.name


def load_sample_scenario():
    """Returns a tuple matching the form's input order."""
    s = SAMPLE_SCENARIO
    return (
        s["num_lines"], s["num_facilities"], s["annual_volume"], s["product_type"],
        s["current_method"], s["clearance_duration"], s["changeovers_per_week"],
        s["deviation_frequency"],
        s["mes_system"], s["ebr_system"], s["equipment_age"],
        s["inspection_outcome"], s["validation_maturity"],
        s["operator_familiarity"], s["prior_attempt"],
        s["labor_rate"], s["time_savings_pct"], s["first_line_cost"],
        s["additional_line_cost"], s["downtime_cost_per_hour"],
    )


# ============================================================================
# UI
# ============================================================================

HEADER_HTML = f"""
<div id="header-banner">
  <h1>{APP_TITLE}</h1>
  <p>{APP_TAGLINE} Built on publicly available 2025 pharma industry benchmark research, which shows that the majority of factories that piloted digital line clearance in earlier years have not yet rolled it out at scale.</p>
</div>
<div id="disclaimer-strip">
  <b>Disclaimer:</b> {APP_DISCLAIMER}
</div>
"""

with gr.Blocks(title=APP_TITLE, css=CUSTOM_CSS) as demo:
    gr.HTML(HEADER_HTML)

    with gr.Row():
        sample_btn = gr.Button("📋 Load sample pharma factory scenario",
                               variant="secondary", size="sm")

    gr.Markdown(
        "### Instructions  \n"
        "Answer the 15 questions below. Sensible defaults are pre-filled — "
        "adjust those that apply. Click *Load sample scenario* for a realistic "
        "mid-case pharma factory. Expand *Advanced assumptions* to override "
        "financial inputs. Click **Run Assessment** for your full assessment.")

    with gr.Accordion("Section 1: Factory Profile", open=True):
        num_lines = gr.Slider(label="Number of production lines in scope for rollout",
            minimum=1, maximum=100, value=10, step=1)
        num_facilities = gr.Slider(label="Number of facilities involved",
            minimum=1, maximum=20, value=2, step=1)
        annual_volume = gr.Radio(label="Approximate annual production volume",
            choices=["Under 1 million units", "1–10 million units",
                "10–100 million units", "Over 100 million units"],
            value="1–10 million units")
        product_type = gr.Radio(label="Primary product type",
            choices=["Oral solid dose", "Injectable", "Biologic", "Medical device", "Other"],
            value="Oral solid dose")

    with gr.Accordion("Section 2: Current Line Clearance Practice", open=True):
        current_method = gr.Radio(label="Current line clearance method",
            choices=list(SCORE_CURRENT_METHOD.keys()),
            value="Hybrid (some digital, some paper)")
        clearance_duration = gr.Radio(label="Average line clearance duration today",
            choices=list(SCORE_CLEARANCE_DURATION.keys()), value="1–2 hours")
        changeovers_per_week = gr.Slider(label="Average number of changeovers per line per week",
            minimum=1, maximum=30, value=5, step=1)
        deviation_frequency = gr.Radio(label="Line clearance deviations in the past 12 months",
            choices=list(SCORE_DEVIATION_FREQUENCY.keys()), value="3–5")

    with gr.Accordion("Section 3: IT and Integration Landscape", open=True):
        mes_system = gr.Radio(label="Existing Manufacturing Execution System (MES)",
            choices=list(SCORE_MES_SYSTEM.keys()), value="None")
        ebr_system = gr.Radio(label="Electronic batch record (eBR) system in place",
            choices=list(SCORE_EBR_SYSTEM.keys()), value="Partial")
        equipment_age = gr.Radio(label="Equipment and PLC age",
            choices=list(SCORE_EQUIPMENT_AGE.keys()),
            value="Mixed (some new, some old)")

    with gr.Accordion("Section 4: Regulatory and Quality Context", open=True):
        inspection_outcome = gr.Radio(label="Last regulatory inspection outcome",
            choices=list(SCORE_INSPECTION_OUTCOME.keys()),
            value="Minor observations")
        validation_maturity = gr.Radio(label="Computer system validation maturity",
            choices=list(SCORE_VALIDATION_MATURITY.keys()),
            value="Functional but ad-hoc")

    with gr.Accordion("Section 5: Workforce and Change-Management Context", open=True):
        operator_familiarity = gr.Radio(label="Operator digital tool familiarity",
            choices=list(SCORE_OPERATOR_FAMILIARITY.keys()), value="Medium")
        prior_attempt = gr.Radio(
            label="Has your facility ever attempted a line clearance digitization project before?",
            choices=list(SCORE_PRIOR_ATTEMPT.keys()),
            value="No — first attempt")

    with gr.Accordion("Advanced assumptions (optional — override defaults)", open=False):
        gr.Markdown("These defaults come from publicly available industry data. "
            "Adjust any of them to reflect your own assumptions.")
        labor_rate = gr.Slider(label="Fully-loaded operator labor rate (USD per hour)",
            minimum=20, maximum=150, value=DEFAULT_LABOR_RATE_USD_PER_HOUR, step=5)
        time_savings_pct = gr.Slider(label="Expected time savings from AI line clearance (%)",
            minimum=10, maximum=85, value=DEFAULT_TIME_SAVINGS_PCT, step=5)
        first_line_cost = gr.Slider(label="First line deployment cost per facility (USD)",
            minimum=30_000, maximum=200_000,
            value=DEFAULT_FIRST_LINE_COST_USD, step=5_000)
        additional_line_cost = gr.Slider(label="Additional line deployment cost (same facility, USD)",
            minimum=20_000, maximum=150_000,
            value=DEFAULT_ADDITIONAL_LINE_COST_USD, step=5_000)
        downtime_cost_per_hour = gr.Slider(
            label="Production downtime cost per hour (USD) — optional, defaults to $0",
            minimum=0, maximum=25_000,
            value=DEFAULT_DOWNTIME_COST_PER_HOUR_USD, step=500)
        gr.Markdown(
            "<small><i>Downtime cost defaults to $0 to keep the base case conservative. "
            "Add your own value to model the additional savings from reduced line "
            "downtime during changeovers.</i></small>")

    submit_btn = gr.Button("Run Assessment", variant="primary", size="lg")

    with gr.Row():
        pdf_btn = gr.Button("📄 Download Executive Summary PDF", variant="secondary")
        pdf_file = gr.File(label="Your PDF will appear here", visible=True)

    headline_out = gr.HTML()
    with gr.Row():
        gauge_out = gr.Plot(label="Readiness Score")
        ladder_out = gr.Plot(label="Sub-score Breakdown")

    gr.Markdown("## Financial Projection (ROI)")
    with gr.Row():
        roi_compare_out = gr.Plot(label="Annual cost: before vs after")
        payback_out = gr.Plot(label="Payback period with break-even marker")
    roi_notes_out = gr.Markdown()

    gr.Markdown("## Risk Heatmap")
    risk_summary_out = gr.Markdown()
    risk_grid_out = gr.Plot(label="8-risk assessment grid")
    risk_detail_out = gr.Markdown()

    recommendations_out = gr.Markdown()

    all_inputs = [
        num_lines, num_facilities, annual_volume, product_type,
        current_method, clearance_duration, changeovers_per_week, deviation_frequency,
        mes_system, ebr_system, equipment_age,
        inspection_outcome, validation_maturity,
        operator_familiarity, prior_attempt,
        labor_rate, time_savings_pct, first_line_cost, additional_line_cost,
        downtime_cost_per_hour,
    ]

    sample_btn.click(fn=load_sample_scenario, inputs=[], outputs=all_inputs)

    submit_btn.click(
        fn=process_form,
        inputs=all_inputs,
        outputs=[
            headline_out, gauge_out, ladder_out,
            roi_compare_out, payback_out, roi_notes_out,
            risk_summary_out, risk_grid_out, risk_detail_out, recommendations_out,
        ],
    )

    pdf_btn.click(
        fn=generate_pdf_for_download,
        inputs=all_inputs,
        outputs=pdf_file,
    )


if __name__ == "__main__":
    demo.launch()